### ISSUE TITLE
Create a Github Action or Actions for Tests

### ISSUE THREAD

**Issue by acouch** [cal-itp/agency-hub#12]
**Background**

The scope of this ticket depends on https://github.com/cal-itp/agency-hub/issues/10 . A Github action or actions should be setup in order to run tests on PRs and code commits. The benefits project has an example of a UI github action we can follow https://github.com/cal-itp/benefits/blob/dev/.github/workflows/tests-ui.yml

**Acceptance criteria**

- [ ] Create a Github action for tests or individual actions, depending on #10 and preference
- [ ] Tests should run on code commits

**Comment by thekaveman** [comment]
I'll also mention, in Benefits we recently added Python unit tests and a workflow to run those: https://github.com/cal-itp/benefits/blob/dev/.github/workflows/tests-pytest.yml
